### ISSUE TITLE
How Data Works 404

### ISSUE THREAD

**Issue by theduke** [dat-ecosystem-archive/datproject.org#1]
The "How Dat Works" link on the homepage link is wrong and gives a 404 error.

**Comment by ninabreznik** [comment]
Hi, @theduke thanks for letting us know. You can access it here for now https://dat-ecosystem-archive.github.io/how-dat-works/

I will try to update the page link as well. Sorry for breaking things, we are in the middle of the archival process, so hope this will cause as little troubble as possible, but there will be hickups sadly.

**Comment by ninabreznik** [comment]
Link should be fixed now, Please let me know if anything else behaves weird.

Thanks

**Comment by theduke** [comment]
Cheers.
